// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtyP7q9ZQTV0PXvlpdBskopC0__pzthH8',
    appId: '1:1081636513876:web:8320e2bac5f99c958225c1',
    messagingSenderId: '1081636513876',
    projectId: 'madrasti-app-1272a',
    authDomain: 'madrasti-app-1272a.firebaseapp.com',
    storageBucket: 'madrasti-app-1272a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ZoxhuGYhwUbY75zDIx3n_UwG-to_JnQ',
    appId: '1:1081636513876:android:e5f259c6c7c1f2608225c1',
    messagingSenderId: '1081636513876',
    projectId: 'madrasti-app-1272a',
    storageBucket: 'madrasti-app-1272a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARHIesb1OJP8cWpuYUuR87H9zA2JPFwSw',
    appId: '1:1081636513876:ios:30b33d474e883eaa8225c1',
    messagingSenderId: '1081636513876',
    projectId: 'madrasti-app-1272a',
    storageBucket: 'madrasti-app-1272a.firebasestorage.app',
    iosBundleId: 'com.alwiam.madrasati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARHIesb1OJP8cWpuYUuR87H9zA2JPFwSw',
    appId: '1:1081636513876:ios:a3a96a3ab4e600bb8225c1',
    messagingSenderId: '1081636513876',
    projectId: 'madrasti-app-1272a',
    storageBucket: 'madrasti-app-1272a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtyP7q9ZQTV0PXvlpdBskopC0__pzthH8',
    appId: '1:1081636513876:web:e2b873fae6045acd8225c1',
    messagingSenderId: '1081636513876',
    projectId: 'madrasti-app-1272a',
    authDomain: 'madrasti-app-1272a.firebaseapp.com',
    storageBucket: 'madrasti-app-1272a.firebasestorage.app',
  );
}
